test_during_training: True 
train_ratio: 0.6
val_ratio: 0.2  
test_ratio: 0.2  

SOC:
  gt_file_path: 'dataset/optical_problems_contrast_change/ground_truth.json'
  IQA_results_path: 'results/IQA_results/'
  root: 'dataset'
